Adding "parent-no-permanent-address" page
codeforamerica/il-gcc-form-flow pull request #107
Opened 2024-03-06 01:02 UTC by sree-cfa

#### 🔗 Pivotal Tracker ticket
PT#187108114

#### ✍️ Description
Adding navigational "parent-no-permanent-address" page 

Not in this PR:
- Skipping tests for now since they depend on the completion of address screens

#### 📷 Design reference
<img width="255" alt="Screenshot 2024-03-05 at 5 00 12 PM" src="https://github.com/codeforamerica/il-gcc-form-flow/assets/72890349/4599f388-80f0-486b-a9c8-0ac9f9c3149f">

2024-03-07 23:49 UTC, enyia21 requested changes
From this [deploy](https://test-il-gcc-pr-107.herokuapp.com/flow/gcc/parent-no-permanent-address) I could not reach the `parent-no-permanent-address` screen

2024-03-07 23:53 UTC, sree-cfa commented on src/main/java/org/ilgcc/app/submission/conditions/ParentIsExperiencingHomelessness.java
> +    return submission.getInputData().getOrDefault("parentHomeExperiencingHomelessness", "false").equals("true");
It's stored here? 
https://github.com/codeforamerica/il-gcc-form-flow/blob/no-permanent-addr/src/main/java/org/ilgcc/app/inputs/Gcc.java#L39

2024-03-07 23:54 UTC, sree-cfa commented on src/main/resources/flows-config.yaml
> +    nextScreens: null
There aren't any inputs on the screen so I left the navigation in the screen itself

2024-03-08 00:19 UTC, enyia21 approved these changes

2024-03-08 00:49 UTC, merged