new unearned-income-amount screen
codeforamerica/il-gcc-form-flow pull request #161
Opened 2024-03-22 21:06 UTC by guiburato

#### 🔗 Pivotal Tracker ticket
[186714238](https://www.pivotaltracker.com/story/show/186714238)

#### ✍️ Description
new unearned-income-amount screen

#### 📷 Design reference
[Figma](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=748-12968&mode=design&t=Mhx1O8zcOqdC2Ct5-0)

#### ✅ Completion tasks

- [ x ] Added relevant tests
- [ x ] Meets acceptance criteria

2024-03-25 18:24 UTC, coltborg commented
Waiting to get [clarification on this design question](https://www.pivotaltracker.com/story/show/186714238/comments/240717848) before approving.

2024-03-25 19:46 UTC, coltborg requested changes

2024-03-25 19:46 UTC, coltborg commented on src/main/resources/templates/gcc/unearned-income-amount.html
> +              <th:block th:replace="~{fragments/inputs/overrides/money :: money(inputName='unearnedIncomeUnemployment', label=#{unearned-income-amount.unemployment}, postfix=#{unearned-income-amount.
It was not mentioned in the ticket, I've now updated it, that these inputs are dynamic and show based on they checkboxes from the previous screen.

Here's a [link to the Figma comments](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8?type=design&node-id=748-12968&mode=design#747453344).

2024-03-27 00:33 UTC, guiburato commented on src/main/resources/templates/gcc/unearned-income-amount.html
> +              <th:block th:replace="~{fragments/inputs/overrides/money :: money(inputName='unearnedIncomeUnemployment', label=#{unearned-income-amount.unemployment}, postfix=#{unearned-income-amount.
@coltborg Thank you for this. I didn't notice it.

2024-03-27 20:43 UTC, coltborg approved these changes
approved!

2024-03-27 20:52 UTC, merged