WIP - Add more date validation to activities program
codeforamerica/il-gcc-form-flow pull request #219
Opened 2024-04-24 22:52 UTC by coltborg

#### 🔗 Jira ticket

#### ✍️ Description

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-04-26 16:55 UTC, rapicastillo commented on src/main/java/org/ilgcc/app/submission/actions/ValidateMonthYearActivitiesProgram.java
> +        String startGroup = "activitiesProgramStart";
Could we define this as a constant?

2024-04-26 17:17 UTC, rapicastillo commented on src/main/resources/messages.properties
> +errors.invalid-date-range=Make sure the date you entered is after 01/01/1901 and before today.
Feels like the error message is the same as `errors.invalid-birthdate-range` but is worded weirdly. Should we have the same verbiage as `errors.invalid-birthdate-range` ?

2024-04-26 17:41 UTC, rapicastillo commented on src/test/java/org/ilgcc/app/submission/actions/ValidateMonthYearActivitiesProgramTest.java
> +    }
Hey! (Pardon if this is nitpicky) but I tried 
```
   ....
    "activitiesProgramStartMonth", "01",
    "activitiesProgramStartDay", "",
    "activitiesProgramStartYear", "1901",
   ...
```

Not sure if this is a bug but this still throws an error (setting end date for the date today does not throw an error, so I was assuming that this is an inclusive between)

2024-04-26 17:42 UTC, rapicastillo reviewed
I'll defer to what @enyia21 says but I left some questions and messages. Thanks Cypress!

2024-04-29 15:43 UTC, coltborg commented on src/main/resources/messages.properties
> +errors.invalid-date-range=Make sure the date you entered is after 01/01/1901 and before today.
Ya, I can align them.

2024-04-29 16:01 UTC, enyia21 requested changes

2024-04-29 16:25 UTC, coltborg commented on src/test/java/org/ilgcc/app/submission/actions/ValidateMonthYearActivitiesProgramTest.java
> +    }
The logic on `01/1901` being inclusive or not is in [the VerifyDate action we're extending](https://github.com/codeforamerica/il-gcc-form-flow/blob/7d8dc7b0c623e43db1536cad84699ca3d6a0fe60/src/main/java/org/ilgcc/app/submission/actions/VerifyDate.java#L21-L28). 


And seeing Carl's message about this in [our stand up zoom](https://us06web.zoom.us/launch/chat/v2/eyJtaWQiOiI3LTExNkQ1N0FBLTEzMkQtNDNFQy1CRTk3LTZBOTg0QTA1RTY2RSIsInNpZCI6IjZjNzdhMjI3OTEyNTQ4OWE5MTI1NDllMDY0N2ZmZGY2QGNvbmZlcmVuY2UueG1wcC56b29tLnVzIiwidGltZSI6MTcxNDQwNzI0NzcxOX0), I'm going to keep it the same for now as this work didn't change the existing behavior.

> "Let’s not worry about it too much. Not many of our dates will actually be on 1/1/1901"

2024-04-29 17:05 UTC, coltborg commented on src/main/java/org/ilgcc/app/submission/actions/ValidateMonthYearActivitiesProgram.java
> +        String endGroup = "activitiesProgramEnd";
Yes, looking into this now

2024-04-29 19:06 UTC, coltborg commented
@rapicastillo / @enyia21, I've made [changes to my PR to address](https://github.com/codeforamerica/il-gcc-form-flow/pull/219/commits/6c15b017344f53aef3aedad4794792033afe536c) the messaging and DRY up the code

2024-04-30 17:04 UTC, enyia21 approved these changes

2024-04-30 17:10 UTC, merged