Implement basic doc upload page and tests
codeforamerica/il-gcc-form-flow pull request #242
Opened 2024-05-08 21:58 UTC by analoo

#### 🔗 Jira ticket
[](https://codeforamerica.atlassian.net/browse/CCAP-33)

#### ✍️ Description
- This ticket introduces the document upload screen
- There is an ability to upload documents
- There is an ability to delete documents in the same UI
- The button stating "I'm done" appears if a file was added.
- Adds test coverage
- No specific code added for event listerers

#### 📷 Design reference
[](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=101-2535&mode=design&t=mwirqS7R1MI4lBZJ-0)

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-05-08 21:59 UTC, analoo commented on src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
> -  @AfterEach
Moved @AfterEach to where it was being used in the tests. We don't need this test tear down to happen after every tests.

2024-05-08 22:05 UTC, analoo commented on src/main/resources/flows-config.yaml
> -    condition: SkipTemplate
removed skip template because otherwise there is no nextScreen for doc-upload-add-files

2024-05-08 22:06 UTC, analoo commented on src/main/resources/messages.properties
> +doc-upload-add-files.accordion-1.body1= <strong>Parent jobs and income</strong><br/>Add two recent pay stubs or an income verification letter for each working parent.
Added each paragraph in its separate string just in case there are copy changes: It will affect a smaller grouping of words rather than all the text.

2024-05-08 22:07 UTC, analoo commented on src/test/java/org/ilgcc/app/utils/AbstractBasePageTest.java
> +  protected void uploadFile(String filepath) {
There are similar methods with different signatures that may be tied to drag and drop.

2024-05-09 20:24 UTC, analoo commented on src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
> +        // doc-upload-add-files
@enyia21 - I believe that the doc-upload-recommended docs is a different ticket: https://codeforamerica.atlassian.net/browse/CCAP-34

2024-05-09 20:45 UTC, enyia21 commented on src/test/java/org/ilgcc/app/journeys/GccFlowJourneyTest.java
> +        // doc-upload-add-files
I think that we create the screen in this ticket, then we add conditional logic in the next ticket. 

![image](https://github.com/codeforamerica/il-gcc-form-flow/assets/46062709/17792859-270f-48a4-8b47-27c863fcc432)

2024-05-13 15:38 UTC, enyia21 requested changes
The copy for`TANF Work Training` is incorrect on the `doc-upload-recommended-docs` screen.  Everything else is good to go

2024-05-13 15:38 UTC, enyia21 commented on src/main/resources/templates/gcc/doc-upload-recommended-docs.html
> +              <p th:utext="#{doc-upload-recommended-docs.school.body}"></p>
I think you meant to `doc-upload-recommended-docs.training.body` instead of `doc-upload-recommended-docs.school.body`.

2024-05-13 16:54 UTC, analoo commented on src/main/resources/templates/gcc/doc-upload-recommended-docs.html
> +              <p th:utext="#{doc-upload-recommended-docs.school.body}"></p>
Thank you! @enyia21

2024-05-13 21:47 UTC, enyia21 approved these changes

2024-05-13 21:54 UTC, merged