CCAP-112 Map children in need of CCAP
codeforamerica/il-gcc-form-flow pull request #316
Opened 2024-06-20 20:50 UTC by enyia21

#### 🔗 Jira ticket

#### ✍️ Description

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-06-21 21:47 UTC, analoo commented on src/test/java/org/ilgcc/app/pdf/NeedChildcareForChildrenPreparerTest.java
> +    void setup(){
do you need this?

2024-06-21 21:51 UTC, analoo requested changes

2024-06-21 21:51 UTC, analoo commented on src/test/java/org/ilgcc/app/utils/SubmissionTestBuilder.java
> +        Map<String, Object> child = children.get(childIterationPosition);
The childIsUSCitizen and childHasSpecial needs fields are not filled out in the filled out pdf. 

Could you update the test to ensure that this is the case?

<img width="1121" alt="Screenshot 2024-06-21 at 2 50 44 PM" src="https://github.com/codeforamerica/il-gcc-form-flow/assets/8609011/0f250bd2-c8c0-4337-8e51-c5a82b4eff3a">

2024-06-21 23:16 UTC, enyia21 commented on src/test/java/org/ilgcc/app/pdf/NeedChildcareForChildrenPreparerTest.java
> +    void setup(){
No need for setup. 
I'm removing it

2024-06-22 00:34 UTC, enyia21 commented on src/test/java/org/ilgcc/app/pdf/NeedChildcareForChildrenPreparerTest.java
> +    void setup(){
Fixed

2024-06-24 18:05 UTC, analoo approved these changes
LGTM.

2024-06-24 18:14 UTC, merged