CCAP-37 Updated withChild() to take needsFinancialAssistanceForChild
codeforamerica/il-gcc-form-flow pull request #329
Opened 2024-06-25 13:47 UTC by enyia21

#### 🔗 Jira ticket
CCAP-37

#### ✍️ Description
- [ ] Updates `withChild()` SubmissionTestBuilder method to include `needsFinancialAssistanceForChild` argument

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-06-26 19:01 UTC, cram-cfa requested changes

2024-06-26 19:01 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java
> +//    try {
Probably want to remove this commented out block, right?

2024-06-26 19:11 UTC, enyia21 commented on src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java
> +//    try {
@cram-cfa I will be removing the blocks as soon as I can get the merge conflicts addressed

2024-06-27 12:43 UTC, enyia21 commented on build.gradle
> +    testImplementation 'io.github.bonigarcia:webdrivermanager:5.9.1'
@cram-cfa [Here](https://github.com/bonigarcia/webdrivermanager/blob/master/CHANGELOG.md#591---2024-06-24) is the changelog for this update.   The change doesn't have an effect our tests.

2024-06-27 14:19 UTC, cram-cfa reviewed
I just have that one question, but otherwise it looks good to me!

2024-06-27 14:19 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/pdf/NeedChildcareForChildren.java
> +    if(earliestCCAPStartDate.isBlank()){
Does this also need to check `&& !childCCAPStartDate.isBlank()` ? What happens if both are blank and we return a blank value here?

The block below, we know that `earliestCCAPStartDate` has a value and isn't blank because it just passed the check here.

2024-06-27 14:54 UTC, cram-cfa approved these changes

2024-06-27 14:55 UTC, merged