activities-ed-program-method screen
codeforamerica/il-gcc-form-flow pull request #33
Opened 2024-02-09 00:17 UTC by guiburato

[#186900927](https://www.pivotaltracker.com/story/show/186900927)

new screen activities-ed-program-method screen

2024-02-12 19:06 UTC, sree-cfa commented
@guiburato can you rebase?

2024-02-12 21:08 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-ed-program-method.html
> +        <th:block th:replace="~{fragments/gcc-icons :: mortarboard}"/>
Looks like this is not needed per Figma

2024-02-12 21:11 UTC, sree-cfa requested changes
- remove icon
- Add "[Program Name]" at the top

2024-02-12 21:14 UTC, sree-cfa commented on src/main/resources/flows-config.yaml
>    activities-ed-program-method:
Can you fix the flow as well? add -> type -> name -> method

2024-02-12 22:32 UTC, guiburato commented on src/main/resources/flows-config.yaml
>    activities-ed-program-method:
Done :)

2024-02-12 22:33 UTC, guiburato commented on src/main/resources/templates/gcc/activities-ed-program-method.html
> +        <th:block th:replace="~{fragments/gcc-icons :: mortarboard}"/>
As we talked, we don't have icons on this screen.

2024-02-12 23:09 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-ed-program-method.html
> +                              label=#{activities-ed-program-method.program.header},
This should be at the card's header/subtext and the ariaLabel can reference that header. ex. https://github.com/codeforamerica/la-doc-uploader/blob/main/src/main/resources/templates/laDigitalAssister/parish.html#L17

2024-02-13 15:15 UTC, guiburato commented on src/main/resources/templates/gcc/activities-ed-program-method.html
> +                              label=#{activities-ed-program-method.program.header},
Thank you, I just changed it.

2024-02-13 20:23 UTC, merged