Activities class weekly schedule 186900934
codeforamerica/il-gcc-form-flow pull request #35
Opened 2024-02-12 22:28 UTC by guiburato

[#186900934](https://www.pivotaltracker.com/story/show/186900934)

- new screen activities-class-weekly-schedule .

2024-02-12 22:32 UTC, sree-cfa commented on src/main/java/org/ilgcc/app/inputs/Gcc.java
> +    private ArrayList<String> weeklySchedule;
```suggestion
    private List<String> weeklySchedule;
```

2024-02-12 22:42 UTC, sree-cfa requested changes
Can you update the journey test?

2024-02-12 22:43 UTC, sree-cfa commented
Missing **[Program Name]** per Figma 
<img width="210" alt="Screenshot 2024-02-12 at 2 42 06 PM" src="https://github.com/codeforamerica/il-gcc-form-flow/assets/72890349/b32d5a7f-c7ca-4dbd-81d0-a5a1e4dc159f">

2024-02-13 20:29 UTC, guiburato commented on src/main/java/org/ilgcc/app/inputs/Gcc.java
> +    private ArrayList<String> weeklySchedule;
Ops.. Good call.

2024-02-13 20:47 UTC, guiburato commented
![Screenshot 2024-02-13 at 3 39 29 PM](https://github.com/codeforamerica/il-gcc-form-flow/assets/81720136/fea33238-f4a1-4a4b-88b0-7ecee9b6e9eb)

2024-02-13 21:18 UTC, sree-cfa approved these changes
lgtm

2024-02-13 21:20 UTC, merged