Ana ccap 352
codeforamerica/il-gcc-form-flow pull request #648
Opened 2024-10-01 16:31 UTC by analoo

#### 🔗 Jira ticket

#### ✍️ Description

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-10-01 16:31 UTC, analoo commented on src/main/java/org/ilgcc/app/inputs/Providerresponse.java
> +import jakarta.validation.constraints.NotEmpty;
to do : Remove

2024-10-01 16:32 UTC, analoo commented on src/main/java/org/ilgcc/app/inputs/Providerresponse.java
> +    private String clientApplicationId;
Added a client Application Id as a way to track which submission this provider response is associated with.

2024-10-01 16:32 UTC, analoo commented on src/main/java/org/ilgcc/app/inputs/Providerresponse.java
> +    private String clientApplicationId;
I don't love the name. Any recommendations?

2024-10-01 16:32 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/FindApplicationData.java
> +        if(clientID != null &&  clientID.isPresent()){
Rather than saving family details in the session, we can get it using the application id.

2024-10-01 16:33 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/SaveApplicationId.java
> +        UUID clientSubmissionId = (UUID) httpSession.getAttribute("clientSubmissionId");
this takes the clientSubmissionId from the httpSession and saves it to the providerResponse

2024-10-01 16:35 UTC, analoo commented on src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
> +    public static Optional<UUID> getClientId(Submission providerSubmission) {
Using this utilities file to modify data to appear how the designs want it to appear.

2024-10-02 00:58 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/SaveApplicationIdFromApplicationId.java
> +    public void run(FormSubmission formSubmission, Submission providerSubmission) {
this solves for the case where the provided did not come from a short link and instead typed in the confirmation id

2024-10-02 01:08 UTC, analoo commented on src/main/resources/templates/providerresponse/application-id.html
> +      var confirmationCode = [[${session.confirmationCode}]];
hmm 🤔

2024-10-02 01:09 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/SaveApplicationIdFromApplicationId.java
> +        Boolean hasApplicationID = providerSubmission.getInputData().containsKey("clientApplicationId");
??? 🤔

2024-10-02 16:14 UTC, analoo commented on src/main/java/org/ilgcc/app/inputs/Providerresponse.java
> +    private String clientApplicationId;
familyApplicationId?

2024-10-02 16:18 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/SaveApplicationIdFromApplicationId.java
> +        Boolean hasApplicationID = providerSubmission.getInputData().containsKey("clientApplicationId");
Change data type from Boolean to boolean.

2024-10-02 20:46 UTC, analoo commented on src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
> +    void providerResponseWithShortLinkFlow() {
to do: remove

2024-10-04 16:02 UTC, cram-cfa requested changes
Just a couple small things, mostly that param on the tests just for accuracy! (The wrong param is just getting tossed away, which isn't a big deal-- just don't want to confuse anyone who searches the code down the line!)

2024-10-04 18:17 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java
> +                if (DAYS.between(submittedAtDate, todaysDate) >= 4) {
Uh - Marc this is technically not accurate actually: "You have 3 business days to respond to a family's application."

2024-10-04 18:48 UTC, analoo commented on src/main/java/org/ilgcc/app/inputs/Gcc.java
> +    private String providerResponseSubmissionId;
Yes :)

2024-10-04 22:20 UTC, cram-cfa requested changes

2024-10-04 22:20 UTC, cram-cfa commented on src/test/java/org/ilgcc/app/journeys/ProviderresponseFlowJourneyTest.java
> +        driver.navigate().to("http://localhost:%s/providerresponse/submit?conf_code=%s&utm_source=test".formatted(localServerPort, CONF_CODE));
@analoo did you want to just change these tests too?

2024-10-04 22:20 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
> +        Map<String, Integer> weekWithOffset = Map.of(
I would pull this out to be a constant that's at the class level, and make it `private final static Map...` 

That's technically "more correct" for Java and it'll save like 1 billionth of 1 billionth of a second, because it'll just be created 1 time and not every single time the method is called.

2024-10-07 21:52 UTC, cram-cfa approved these changes

2024-10-07 21:54 UTC, merged