Activities class hourly schedule 186900938
codeforamerica/il-gcc-form-flow pull request #69
Opened 2024-02-23 00:16 UTC by guiburato

#### 🔗 Pivotal Tracker ticket
[186900938](https://www.pivotaltracker.com/story/show/186900938)

#### ✍️ Description
 - Create new Activities class hourly schedule screen 
 - new Time Range fragment

#### 📷 Design reference
[screen](https://www.figma.com/file/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Full-Flow-(WIP)?type=design&node-id=748-12965&mode=design&t=BcmpDewf3UcXB1Ms-0)

#### ✅ Completion tasks

- [ x ] Added relevant tests
- [ x ] Meets acceptance criteria
- [ x ] Added testing instructions to ticket

2024-02-23 00:55 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +                </th:block>
I think we should follow this pattern of only showing one input if this box is checked
<img width="229" alt="Screenshot 2024-02-22 at 4 50 06 PM" src="https://github.com/codeforamerica/il-gcc-form-flow/assets/72890349/88e0b653-8ff2-4655-a2b5-7adcdf25526d">

2024-02-23 01:02 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +              <th:block th:replace="~{fragments/inputs/timeRange :: timeRange(startInputName='startTimeFriday', endInputName='endTimeFriday', label=#{general.week.friday})}" />
I think these should only show based on what the client checked on the previous screen

2024-02-23 14:46 UTC, guiburato commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +              <th:block th:replace="~{fragments/inputs/timeRange :: timeRange(startInputName='startTimeFriday', endInputName='endTimeFriday', label=#{general.week.friday})}" />
Yes, I just changed.

2024-02-27 16:25 UTC, sree-cfa commented on src/main/java/org/ilgcc/app/inputs/Gcc.java
> +    private String endTimeFriday;
Can we rename these to "classStartTime.."? We have a few other places that have hourly schedules as well

2024-02-27 16:26 UTC, sree-cfa commented on src/main/resources/static/assets/css/custom.css
> +
Can this be formatted pretty-print?

2024-02-27 16:36 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +                <th:block th:replace="~{fragments/inputs/timeRange :: timeRange(startInputName='startTime' + ${day}, endInputName='endTime' + ${day}, label=#{${'general.week.' + day}})}" />
Nice! 
It looks like "weeklySchedule" values are lowerCase ex "monday", so the inputs here will be "startTimemonday" instead of "startTimeMonday" - one of them should be updated to match since these fields are case-sensitive

2024-02-27 16:44 UTC, sree-cfa commented
Let's double check w Catalina/Carlie if this follow-up pattern looks ok.

Other TODOs From acceptance criteria
- Hide individual fields when "same every day" box is checked
- Format day of week header when checkbox is checked - ex. "Monday-Thursday", "Monday, Wednesday, Friday"
<img width="500" alt="Screenshot 2024-02-27 at 8 32 28 AM" src="https://github.com/codeforamerica/il-gcc-form-flow/assets/72890349/a3231803-4fc1-4c48-a259-e74a2c47dbd5">

2024-02-27 16:45 UTC, sree-cfa requested changes
Left some comments about changes

2024-02-27 20:07 UTC, guiburato commented on src/main/resources/static/assets/css/custom.css
> +
Done. :)

2024-02-27 20:13 UTC, guiburato commented on src/main/java/org/ilgcc/app/inputs/Gcc.java
> +    private String endTimeFriday;
Done. :)

2024-02-27 20:24 UTC, guiburato commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +                <th:block th:replace="~{fragments/inputs/timeRange :: timeRange(startInputName='startTime' + ${day}, endInputName='endTime' + ${day}, label=#{${'general.week.' + day}})}" />
Done. :)

2024-02-28 17:10 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +</script>
We can also just add a handler here without making FFL changes
```suggestion
<script th:inline="javascript">
    $(document).ready(function () {
        $('#activitiesClassHoursSameEveryDay-true').change(function () {
            $('#grouped-days').toggleClass('hidden');
            $('#individual-days').toggleClass('hidden');
        });
    });
</script>
```

2024-02-28 17:18 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +                      <th:block
We can use a single "checkbox" here instead of the "checkboxInSet"
See https://github.com/codeforamerica/form-flow?tab=readme-ov-file#checkbox-1
```
<th:block th:replace="~{fragments/inputs/checkbox ::
                checkbox(inputName='activitiesClassHoursSameEveryDay',
                  value='true',
                  label=#{activities-class-hourly-schedule.class.hours.same.every.day})}"/>
```

2024-02-28 17:20 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +              </div>
Somewhere above we can use the checkbox value to set the initial state
```
th:with="isSameEveryDay=${!#lists.isEmpty(fieldData.get('activitiesClassHoursSameEveryDay[]'))}">
```
```suggestion
<div id="grouped-days" th:class="${isSameEveryDay ? '' : 'hidden'}">
                <th:block th:replace="~{fragments/inputs/timeRange ::
                  timeRange(startInputName='activitiesClassStartTimeAllDays',
                    endInputName='activitiesClassEndTimeAllDays',
                    label=#{general.week.All})}"/>
              </div>
```

2024-02-28 23:10 UTC, guiburato commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +                      <th:block
Done.

2024-02-28 23:15 UTC, guiburato commented on src/main/resources/templates/gcc/activities-class-hourly-schedule.html
> +              </div>
Done.

2024-02-28 23:22 UTC, sree-cfa commented on src/main/resources/templates/gcc/activities-ed-program-dates.html
> +                <!-- Put inputs here -->‰
```suggestion
                <!-- Put inputs here -->
```

2024-02-28 23:28 UTC, sree-cfa approved these changes
lgtm

2024-02-28 23:32 UTC, merged