[CCAP-355] Discourage providers from declining care
codeforamerica/il-gcc-form-flow pull request #723
Opened 2024-10-23 23:22 UTC by spokenbird

#### 🔗 Jira ticket
CCAP-355

#### ✍️ Description
Adds a confirmation screen when provider declines to provide care.

#### 📷 Design reference
https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Full-Flow?node-id=9983-25668&t=E36qtaE8FbyiBlAi-4

2024-10-24 20:48 UTC, cram-cfa requested changes
Looks good other than the spelling of that method name and the related test case!

Thanks for including tests!!

2024-10-24 20:48 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
> +    public static String formatChildNamesAsComaSeperatedList(Submission applicantSubmission) {
You're missing an `m` here and also `Separated` not `Seperated`. Should be `commaSeparatedList`

2024-10-24 20:48 UTC, cram-cfa commented on src/test/java/org/ilgcc/app/utils/ProviderSubmissionUtilitiesTest.java
> +    void formatChildNamesAsComaSeperatedList() {
Same on the spelling.

2024-10-29 14:06 UTC, cram-cfa approved these changes

2024-10-29 15:57 UTC, analoo approved these changes

2024-10-29 15:58 UTC, analoo commented
I appreciate the tests and thee child name helper method that lists out the names of children in a grammatically correct way.

2024-10-29 18:03 UTC, merged