Ccap 436 implement link shortening
codeforamerica/il-gcc-form-flow pull request #781
Opened 2024-11-08 19:51 UTC by analoo

#### 🔗 Jira ticket

#### ✍️ Description

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-11-08 19:54 UTC, analoo commented on src/main/java/org/ilgcc/app/links/LinkShortener.java
> +                    .addHeader("Authorization", System.getenv("SHORT_IO_API_KEY"))
@spokenbird - I tried using the value annotation to get the API key and domain key but it kept returning null.

2024-11-08 23:45 UTC, enyia21 requested changes
the method `getShortLink` should be removed from this PR

2024-11-08 23:45 UTC, enyia21 commented on src/main/java/org/ilgcc/app/links/LinkShortener.java
> +    public static String getShortLink(String longLink) {
This method is not used and should be removed from this PR

2024-11-09 00:10 UTC, enyia21 approved these changes

2024-11-12 19:43 UTC, merged