[CCAP-453] Update content on providerresponse/provider-number screen
codeforamerica/il-gcc-form-flow pull request #869
Opened 2024-12-02 23:36 UTC by cram-cfa

#### 🔗 Jira ticket

#### ✍️ Description
<img width="300" alt="Screenshot 2024-12-02 at 5 35 04 PM" src="https://github.com/user-attachments/assets/848281d2-c8a3-43a8-b221-3cb9fbf854ae">
<img width="300" alt="Screenshot 2024-12-02 at 5 35 14 PM" src="https://github.com/user-attachments/assets/34333c7c-d3d9-4c51-bb5a-27cecc676ff5">
<img width="300" alt="Screenshot 2024-12-02 at 5 35 20 PM" src="https://github.com/user-attachments/assets/5bf8708f-f335-4b78-84c4-3c15091cf713">
<img width="300" alt="Screenshot 2024-12-02 at 5 35 28 PM" src="https://github.com/user-attachments/assets/c75c709f-c24b-416f-b020-fd12ace2fa70">
<img width="300" alt="Screenshot 2024-12-02 at 5 35 44 PM" src="https://github.com/user-attachments/assets/da7c7f4a-28dc-45ec-b66e-32baf1223cc4">

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-12-03 16:13 UTC, cram-cfa commented on src/main/resources/templates/fragments/inputs/screenWithOneInputAndSkip.html
> +                  <a th:if="${hasSkipLocation}"
This was apparently always broken, fwiw.

2024-12-03 16:14 UTC, cram-cfa commented on src/main/resources/messages.properties
> +onboarding-provider-info-confirm.notice=<div class='notice--success spacing-below-60'><p>At the end of this application, you''ll have the option to <strong>text or email a secure link</strong> to '{0
I noticed this typo, missing the double apostrophe, when clicking through the app and fixed it here.

2024-12-04 04:38 UTC, analoo commented on src/main/java/org/ilgcc/app/submission/actions/ValidateProviderNumber.java
> +            if (inputValue == null || inputValue.isBlank()) {
I love the most specific error messages here. I think it makes it much clearer what the actual issue is.

2024-12-04 05:04 UTC, analoo commented on src/main/java/org/ilgcc/app/data/ProviderRepository.java
> +    @Query(value = "SELECT CASE WHEN COUNT(*) > 0 THEN TRUE ELSE FALSE END FROM providers "
I tunneled into staging and tested this query using psql. the test worked :)

2024-12-04 05:09 UTC, analoo commented on src/main/resources/messages.properties
> +provider-response-provider-number.no-provider-number=I don't have a provider number.
```suggestion

```

nit: we can probably remove this now since aren't giving people the option to select the link

2024-12-04 05:18 UTC, analoo commented on src/main/resources/flows-config.yaml
> +      - name: provider-number
@spokenbird - heads up that this PR is actually renaming the ccap-registration screen to provider-number so it will actually always appear at the beginning of the flow. This means that you probably no longer need to add the GenerateDummyClientSubmissionForDev to the paid by CCAP screen

2024-12-04 05:23 UTC, analoo commented on src/main/resources/messages.properties
> +onboarding-provider-info-confirm.notice=<div class='notice--success spacing-below-60'><p>At the end of this application, you''ll have the option to <strong>text or email a secure link</strong> to '{0
Thank you for fixing this.

2024-12-04 05:30 UTC, analoo requested changes
Tested the query ✅ , Reviewed the provider-number screen ✅ , confirmed that the link to saying no provider is gone and now on the provider-number screen ✅ 

Made a few recommended changes. The only blocking one is related to the missing apostrophe on provider-info-confirm

2024-12-04 05:31 UTC, analoo commented on src/main/resources/messages.properties
> +onboarding-provider-info-confirm.notice=<div class='notice--success spacing-below-60'><p>At the end of this application, you''ll have the option to <strong>text or email a secure link</strong> to '{0
```suggestion
onboarding-provider-info-confirm.notice=<div class='notice--success spacing-below-60'><p>At the end of this application, you'''ll have the option to <strong>text or email a secure link</strong> to '{0}'.</p><p>Using the link, your provider can quickly complete their part of the application.</p></div>
```

2024-12-04 05:32 UTC, analoo commented on src/main/resources/messages.properties
> +onboarding-provider-info-confirm.notice=<div class='notice--success spacing-below-60'><p>At the end of this application, you''ll have the option to <strong>text or email a secure link</strong> to '{0
<img width="474" alt="Screenshot 2024-12-03 at 9 31 34 PM" src="https://github.com/user-attachments/assets/319f5a73-8933-484c-a4e8-854ad1065eb3">
Leaving with only 2 single quotes breaks the parameter so we need a third quote.

2024-12-04 05:32 UTC, analoo approved these changes
Approving with the request that the suggestions are included.

2024-12-04 15:59 UTC, merged