Ccap 484 map new provider type [TEST PR DO NOT MERGE]
codeforamerica/il-gcc-form-flow pull request #921
Opened 2024-12-16 20:56 UTC by ShaynaCummings

#### 🔗 Jira ticket

#### ✍️ Description

#### 📷 Design reference

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

2024-12-17 15:12 UTC, cram-cfa commented
@ShaynaCummings @enyia21 do we need this PR still? Or can we close it? Thanks!

2024-12-17 15:16 UTC, cram-cfa commented on src/main/resources/application-demo.yaml
> +  allow-provider-registration-flow: ${ALLOW_PROVIDER_REGISTRATION_FLOW:true}
We shouldn't ever need to do this. Just use the Heroku variables and set these directly on those deployments using GENERATE_SHORT_LINKS_FLAG, SHOW_NO_PROVIDER_FLOW, and ALLOW_PROVIDER_REGISTRATION_FLOW

2024-12-19 15:20 UTC, enyia21 commented on src/main/resources/application-demo.yaml
> +  allow-provider-registration-flow: ${ALLOW_PROVIDER_REGISTRATION_FLOW:false}
@cram-cfa I already have the variables set on Heroku.  When you say this is not necessary do you mean that presetting these flags in demo to false is unnecessary?

2024-12-19 15:30 UTC, cram-cfa commented on src/main/resources/application-demo.yaml
> +  allow-provider-registration-flow: ${ALLOW_PROVIDER_REGISTRATION_FLOW:false}
Yep, there's no need to preset the flags in demo to false. 

the default `application.yaml` has this:

```il-gcc:
  app-version: ${APTIBLE_GIT_REF:no-version-set}
  generate-short-links: ${GENERATE_SHORT_LINKS_FLAG:false}
  show-no-provider-flow: ${SHOW_NO_PROVIDER_FLOW:true}
  allow-provider-registration-flow: ${ALLOW_PROVIDER_REGISTRATION_FLOW:false}```
  
which means that both `generate-short-links` and `allow-provider-registration-flow` already default to `false` in all environments.

but yeah, because all three of these read from the variables -- `GENERATE_SHORT_LINKS_FLAG`, `SHOW_NO_PROVIDER_FLOW`, and  `ALLOW_PROVIDER_REGISTRATION_FLOW` -- if they are set in Heroku (or Aptible) there's no reason to modify the `application-demo.yaml`. 

You should just set that variables in Heroku (either on your instance, or in the base template so all Heroku deployments get the value) and not modify the yaml file IMO.

2024-12-19 16:59 UTC, enyia21 commented on src/main/resources/application-demo.yaml
> +  allow-provider-registration-flow: ${ALLOW_PROVIDER_REGISTRATION_FLOW:false}
@cram-cfa I don't know how to change the variables for individual deploys.  My understanding of the Heroku config setup is that you change the variables for the app/environment and this will change it for every deploy made in the environment.  In this case `demo`.

2024-12-19 19:31 UTC, cram-cfa requested changes

2024-12-19 19:31 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
>              return Optional.of(UUID.fromString(applicantID));
I'm not sure I understand this change to the logic here. 

If `familySubmissionId` is null and `clientResponseConfirmationCode` is not null, you'll wind up getting a `null` on line 51 for `applicantID`... and then line 52 will give a NullPointerException because `applicantID` is null.

What are you accomplishing by checking if `clientResponseConfirmationCode` is not null and exists, but then not using it for anything?

2024-12-19 19:31 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java
> +                submissionRepositoryService.save(submission);
Two questions/thoughts here:

1. I do not see `shortCodeClientSubmissionId` used anywhere in this PR, or anywhere in the codebase. So, do we need to do this at all? But, if we do...

2. Why can't we use the name `familySubmissionId`? This is what it is called in the `SaveApplicationId` action on line 27, and this is the exact same value. 

But, again, I think point 1 is the issue here-- I don't see where this is used anywhere, so what are we doing with this?

2024-12-19 19:31 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/submission/actions/CheckClientSubmissionForProvider.java
> +                submissionRepositoryService.save(clientSubmissionInfo);
I would just save this value as `providerResponseSubmissionId`. We already use that elsewhere, and that's exactly what this is-- I can't see any reason why we'd actually need to store it separately, as our current flow only allows 1 fully completed provider response submission to correlate to a fully completed family submission. 

If a provider starts responding and then quits and then comes back a day later and starts responding to the same family submission, I don't know why we'd want to have the first attempt as `providerResponseSubmissionId` and now the second attempt as `tempProviderResponseSubmissionId`... because somewhere along the flow the code will re-set `providerResponseSubmissionId` to the new value anywhere.

2024-12-19 19:31 UTC, cram-cfa commented on src/main/java/org/ilgcc/app/utils/ProviderSubmissionUtilities.java
> +        }
I think we could just always set the value to be `providerResponseSubmissionId` in `CheckClientSubmissionForProvider` and then we don't need this new block of code.

2024-12-19 22:45 UTC, closed without merging